[GeneralSettings]
LocalStorageEnabled=True
ScreenCaptureEnabled=True
PluginsEnabled=true
WebGLEnabled=True
Accelerated2dCanvasEnabled=True
JavascriptEnabled=true
PdfViewerEnabled=True
JavascriptCanAccessClipboard=false
PlaybackRequiresUserGesture=true
SaveCookies=True
AskWhereSaveDownload=true
PathSaveCookies=./cookies
DefaultSearchEngine=duckduckgo.com
DownloadPath=./cache_aux
ForceDarkMode=true
HomePage=https://www.google.com/
SearchEngine="https://www.google.com/search?q={}"
